import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:agrolink/core/utils/helpers.dart';
import 'package:agrolink/models/farmer_model.dart';
import 'package:agrolink/models/visit_model.dart';

class PdfGenerator {
  static Future<void> generateAndPrintAnalyticsReport({
    required String month,
    required double totalRevenue,
    required int totalVisits,
    required int newFarmers,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('AgroLink', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.green800)),
                      pw.Text('Smart Agriculture Consultation', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Monthly Analytics Report', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                      pw.Text('Period: $month', style: const pw.TextStyle(fontSize: 12)),
                      pw.Text('Generated: ${AppHelpers.formatDate(DateTime.now())}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 30),
              pw.Divider(),
              pw.SizedBox(height: 20),

              // KPI Summary
              pw.Text('Executive Summary', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.green700)),
              pw.SizedBox(height: 15),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _buildKpiBox('Total Revenue', 'Rs. ${totalRevenue.toStringAsFixed(0)}'),
                  _buildKpiBox('Total Visits', totalVisits.toString()),
                  _buildKpiBox('New Farmers', newFarmers.toString()),
                  _buildKpiBox('Avg. Fee', 'Rs. ${(totalRevenue / (totalVisits > 0 ? totalVisits : 1)).toStringAsFixed(0)}'),
                ],
              ),
              pw.SizedBox(height: 30),

              // Top Villages
              pw.Text('Top Performing Villages', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.green700)),
              pw.SizedBox(height: 10),
              pw.Table.fromTextArray(
                context: context,
                border: const pw.TableBorder(
                  bottom: pw.BorderSide(color: PdfColors.grey300, width: .5),
                  horizontalInside: pw.BorderSide(color: PdfColors.grey300, width: .5),
                ),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.green600),
                cellAlignment: pw.Alignment.centerLeft,
                data: <List<String>>[
                  ['Village', 'Farmers Active', 'Visits Conducted'],
                  ['Shirur', '85', '42'],
                  ['Baramati', '62', '28'],
                  ['Indapur', '48', '15'],
                  ['Daund', '35', '10'],
                ],
              ),
              
              pw.SizedBox(height: 30),
              // Disclaimer
              pw.Spacer(),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Center(
                child: pw.Text('This report is automatically generated by AgroLink. For internal use only.',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'AgroLink_Report_$month.pdf',
    );
  }

  static pw.Widget _buildKpiBox(String title, String value) {
    return pw.Container(
      width: 110,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(value, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.green800)),
          pw.SizedBox(height: 4),
          pw.Text(title, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
        ],
      ),
    );
  }
}
